title: John Doe # your name (or website title) here
logo: "/images/github_profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Deverloper who wants to be lifesaver 
  <br><br>
  MOTTO: 君子厚积薄发,一期一会,Simple is beautiful
  <br><br>
  <a href="https://www.linkedin.com/in/yanghaoyuying/">Check my linkedin page!</a> 
  
theme: jekyll-theme-minimal
