title: Howard (Yang Hao)
logo: "/images/github_profile.png?raw=true"
description: >
  Deverloper who wants to be lifesaver 
  <br><br>
  MOTTO: 君子厚积薄发,一期一会,Simple is beautiful
  <br><br>
  <a href="https://www.linkedin.com/in/yanghaoyuying/">Check my linkedin page!</a> 
