title: Howard(Yang Hao)
logo: "/images/github_profile.png?raw=true"
description: >
  GOAL: Deverloper who wants to be a lifesaver
  <br><br>
  MOTTO: 君子厚积薄发(Spur with long accumulation), 一期一会(Encounter of a lifetime), Simple is beautiful
  <br><br>
  ABOUT ME:
    7+ years of studying and working experience(2+ years) in Japan, native proficiency in (Japanese, English, Chinese)
    Dedicated and efficient web developer with 4+ years experience in application layers, presentation layers, and databases.
    Certified in both F/E and B/E technologies.
    Technology I’ve used: Ruby, Node.js, Python, JavaScript, React, Angular, Mysql, MongoDB, Docker, Redis, Unix, etc.
    Likes jogging, exercise and learning new technologies.
  <br><br>
  <a href="https://www.linkedin.com/in/yanghaoyuying/">Linkedin</a>
  <a href="https://www.facebook.com/yanghaoyuying">Facebook</a>
  <a href="https://twitter.com/yanghaoyuying/">Twitter</a>
  <a href="https://haoomedia.wordpress.com/">Haoomedia</a>
